import { ClientEvent } from '@public/shared/event/client';

import { Job, JobPermission, JobPermissionData, JobType } from '../job';
import { BoxZone, Zone } from '../polyzone/box.zone';

const BasePermissions: Partial<Record<JobPermission, JobPermissionData>> = {
    [JobPermission.Enrollment]: { label: 'Quản lý tuyển dụng' },
    [JobPermission.ManageGrade]: { label: 'Quản lý cấp bậc' },
    [JobPermission.SocietyBankAccount]: { label: 'Truy cập tài khoản ngân hàng doanh nghiệp' },
    [JobPermission.SocietyBankInvoices]: { label: 'Truy cập công cụ xuất hóa đơn' },
    [JobPermission.SocietyPrivateStorage]: { label: 'Truy cập kho giám đốc (Boss)' },
    [JobPermission.SocietyGeneralStorage]: { label: 'Truy cập kho lưu trữ chung' },
    [JobPermission.SocietyMoneyStorage]: { label: 'Truy cập két sắt doanh nghiệp' },
    [JobPermission.SocietyDealershipVehicle]: { label: 'Truy cập đại lý mua xe doanh nghiệp' },
    [JobPermission.SocietyTakeOutPound]: { label: 'Lấy xe ra khỏi bãi tạm giữ' },
    [JobPermission.SocietyPublicGarage]: {
        label: 'Cất / Lấy xe từ gara công cộng',
    },
    [JobPermission.SocietyPrivateGarage]: {
        label: 'Cất / Lấy xe từ gara riêng',
    },
    [JobPermission.SocietyPublicPort]: { label: 'Cất / Lấy thuyền từ bến cảng công cộng' },
    [JobPermission.SocietyPrivatePort]: { label: 'Cất / Lấy thuyền từ bến cảng riêng' },
    [JobPermission.SocietyShop]: { label: 'Truy cập cửa hàng nội bộ doanh nghiệp' },
    [JobPermission.OnDutyView]: { label: 'Xem nhân viên đang trong ca trực' },
    [JobPermission.SocietyViewCompanyPanel]: { label: 'Truy cập bảng điều khiển giám đốc' },
};

const CompanyPanelPermissions: Partial<Record<JobPermission, JobPermissionData>> = {
    [JobPermission.NewCompanyPanelAccess]: { label: 'Truy cập bảng quản trị công ty' },
    [JobPermission.EmployeesListRead]: { label: 'Xem dữ liệu nhân viên trên panel' },
    [JobPermission.EmployeesListWrite]: { label: 'Chỉnh sửa dữ liệu nhân viên trên panel' },
    [JobPermission.PricingRead]: { label: 'Xem bảng báo giá trên panel' },
    [JobPermission.PricingManage]: { label: 'Quản lý bảng báo giá trên panel' },
    [JobPermission.ReadDocumentation]: { label: 'Đọc tài liệu hướng dẫn trên panel' },
    [JobPermission.WriteDocumentation]: { label: 'Chỉnh sửa tài liệu trên panel' },
    [JobPermission.ManageDocumentation]: { label: 'Quản lý tài liệu trên panel' },
    [JobPermission.AssignCertification]: { label: 'Phân công khóa đào tạo trên panel' },
    [JobPermission.ManageCertification]: { label: 'Quản lý khóa đào tạo trên panel' },
    [JobPermission.ManageRoster]: { label: 'Quản lý ảnh nhân sự trên panel' },
};

const PolicePermissions: Partial<Record<JobPermission, JobPermissionData>> = {
    [JobPermission.CriminalRecord]: { label: 'Truy cập hồ sơ tiền án tiền sự' },
    [JobPermission.VehicleRegistrar]: { label: 'Truy cập sổ đăng ký phương tiện' },
    [JobPermission.VehicleTransfert]: { label: 'Truy cập chuyển nhượng phương tiện' },
    [JobPermission.Investigation]: { label: 'Truy cập hồ sơ điều tra' },
    [JobPermission.ManageInvestigation]: { label: 'Quản lý hồ sơ điều tra' },
    [JobPermission.AssignCertification]: { label: 'Cấp chứng chỉ nghiệp vụ cho sĩ quan' },
    [JobPermission.ManageCertification]: { label: 'Quản lý chứng chỉ nghiệp vụ' },
    [JobPermission.ManageRoster]: { label: 'Quản lý ảnh/mã số sĩ quan trên panel' },
    [JobPermission.FDOFedPound]: { label: 'Tạm giữ phương tiện cấp Liên bang' },
};

const NewsPermissions: Partial<Record<JobPermission, JobPermissionData>> = {
    [JobPermission.NewsManageArticle]: { label: 'Quản lý bài báo trên panel' },
    [JobPermission.NewsManageBillboards]: { label: 'Quản lý bảng quảng cáo trên panel' },
    [JobPermission.NewsCreateBillboard]: { label: 'Đặt / Phá dỡ bảng quảng cáo động' },
    [JobPermission.NewsUpdateBillboard]: { label: 'Chỉnh sửa bảng quảng cáo động' },
};

export const JobRegistry: Record<JobType, Omit<Job, 'id'>> = {
    [JobType.Unemployed]: {
        label: 'Tự do / Thất nghiệp',
        permissions: {},
        canReceiveSocietyInvoice: false,
    },
    [JobType.Adsl]: {
        label: 'Viễn thông ADSL',
        platePrefix: 'ADSL',
        permissions: {},
        canReceiveSocietyInvoice: false,
    },
    [JobType.Delivery]: {
        label: 'Giao hàng nhanh (Delivery)',
        platePrefix: 'FOUG',
        permissions: {},
        canReceiveSocietyInvoice: false,
    },
    [JobType.Religious]: {
        label: 'Tôn giáo & Cứu trợ (InfoChat)',
        platePrefix: 'INFO',
        permissions: {},
        canReceiveSocietyInvoice: false,
    },
    [JobType.Scrapper]: {
        label: 'Thu gom phế liệu (OldMetal)',
        platePrefix: 'OMC',
        permissions: {},
        canReceiveSocietyInvoice: false,
    },
    [JobType.FBI]: {
        label: 'Cục Điều tra Liên bang (FBI)',
        platePrefix: 'FBI ',
        menuCallback: ClientEvent.JOBS_POLICE_OPEN_SOCIETY_MENU,
        permissions: {
            [JobPermission.SocietyDealershipVehicle]: { label: 'Truy cập đại lý mua xe doanh nghiệp' },
        },
        phone: '555-FBI',
        canReceiveSocietyInvoice: true,
    },
    [JobType.LSPD]: {
        label: 'Sở Cảnh sát Los Santos (LSPD)',
        platePrefix: 'LSPD',
        menuCallback: ClientEvent.JOBS_POLICE_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            ...PolicePermissions,
        },
        bossZones: [
            {
                center: [466.47, -975.26, 35.94],
                length: 8.8,
                width: 11.0,
                heading: 87.9,
                minZ: 34.94,
                maxZ: 36.94,
            },
            // MIRROR PARK
            {
                center: [1147.86, -466.25, 72.62],
                length: 28.2,
                width: 33.6,
                heading: 166.7,
                minZ: 71.62,
                maxZ: 73.62,
            },
        ],
        phone: '555-LSPD',
        canReceiveSocietyInvoice: true,
    },
    [JobType.BCSO]: {
        label: 'Blaine County Sheriff Office',
        platePrefix: 'BCSO',
        menuCallback: ClientEvent.JOBS_POLICE_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            ...PolicePermissions,
        },
        bossZones: [
            {
                center: [1855.38, 3689.22, 38.07],
                length: 3.8,
                width: 6.8,
                heading: 30,
                minZ: 37.07,
                maxZ: 41.01,
            },
            // MIRROR PARK
            {
                center: [1147.86, -466.25, 72.62],
                length: 28.2,
                width: 33.6,
                heading: 166.7,
                minZ: 71.62,
                maxZ: 73.62,
            },
        ],
        phone: '555-BCSO',
        canReceiveSocietyInvoice: true,
    },
    [JobType.LSCS]: {
        label: 'Los Santos County Sheriff',
        platePrefix: 'LSCS',
        menuCallback: 'soz-jobs:client:police:OpenSocietyMenu',
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            ...PolicePermissions,
        },
        bossZones: [
            {
                center: [447.71, -977.18, 30.69],
                length: 12.4,
                width: 10.0,
                heading: 89.94,
                minZ: 29.69,
                maxZ: 31.69,
            },
        ],
        phone: '555-LCCS',
        canReceiveSocietyInvoice: true,
    },
    [JobType.LSMC]: {
        label: 'Trung tâm Y tế Los Santos (LSMC)',
        platePrefix: 'LSMC',
        menuCallback: ClientEvent.JOBS_LSMC_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.MedicalPatientAccess]: { label: 'Truy cập hồ sơ bệnh nhân trên panel' },
            [JobPermission.MedicalPatientEdit]: { label: 'Chỉnh sửa hồ sơ bệnh nhân trên panel' },
            [JobPermission.MedicalPatientDelete]: { label: 'Xóa hồ sơ bệnh nhân trên panel' },
            [JobPermission.MedicalPatientHistoryAccess]: { label: 'Truy cập lịch sử ca cấp cứu trên panel' },
            [JobPermission.MedicalPatientHistoryEdit]: { label: 'Tạo / Chỉnh sửa ca cấp cứu trên panel' },
            [JobPermission.MedicalPatientHistoryDelete]: { label: 'Xóa ca cấp cứu trên panel' },
            [JobPermission.ManageRoster]: { label: 'Quản lý ảnh/mã số bác sĩ trên panel' },
            [JobPermission.AssignCertification]: { label: 'Cấp chứng chỉ nghiệp vụ y tế' },
            [JobPermission.ManageCertification]: { label: 'Quản lý chứng chỉ nghiệp vụ y tế' },
            [JobPermission.EmployeesListRead]: { label: 'Xem danh sách bác sĩ trên panel y tế' },
            [JobPermission.EmployeesListWrite]: { label: 'Chỉnh sửa hồ sơ bác sĩ trên panel y tế' },
            [JobPermission.ReadDocumentation]: { label: 'Đọc tài liệu hướng dẫn y tế trên panel' },
            [JobPermission.WriteDocumentation]: { label: 'Chỉnh sửa tài liệu y tế trên panel' },
            [JobPermission.ManageDocumentation]: { label: 'Quản lý tài liệu y tế trên panel' },
            [JobPermission.MedicalPsyConsultAccess]: { label: 'Xem hồ sơ khám tâm lý trên panel y tế' },
        },
        bossZones: [
            new BoxZone([383.87, -1411.63, 37.99], 21.0, 25.6, {
                heading: 50.09,
                minZ: 36.99,
                maxZ: 38.99,
            }),
            new BoxZone([1825.73, 3675.86, 38.28], 4.4, 7.4, {
                heading: 27.32,
                minZ: 37.28,
                maxZ: 39.28,
            }),
        ],
        phone: '555-LSMC',
        canReceiveSocietyInvoice: true,
    },
    [JobType.Taxi]: {
        label: 'Dịch vụ Taxi (Carl Jr)',
        platePrefix: 'CARL',
        menuCallback: ClientEvent.JOBS_TAXI_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            ...CompanyPanelPermissions,
        },
        bossZones: [
            {
                center: [907.35, -152.04, 74.17],
                length: 8.4,
                width: 4.2,
                heading: 58,
                minZ: 73.17,
                maxZ: 77.17,
            },
        ],
        phone: '555-CARLJR',
        canReceiveSocietyInvoice: true,
        taxCollectAccounts: ['taxi', 'safe_taxi'],
    },
    [JobType.Food]: {
        label: 'Nhà hàng ẩm thực (Château Marius)',
        platePrefix: 'CHAT',
        menuCallback: ClientEvent.JOBS_FOOD_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.Harvest]: { label: 'Thu hoạch nguyên liệu thực phẩm' },
            [JobPermission.Craft]: { label: 'Nấu ăn & Chế biến món' },
            ...CompanyPanelPermissions,
        },
        resell: {
            coords: [-57.01, -2448.4, 7.24, 145.77],
            ZoneName: 'Resell:LSPort:Food',
            SourceAccount: 'farm_food',
            TargetAccount: 'safe_food',
        },
        bossZones: [
            {
                center: [-1874.49, 2055.03, 154.49],
                length: 6.0,
                width: 5.8,
                heading: 159.29,
                minZ: 153.49,
                maxZ: 155.49,
            },
        ],
        phone: '555-MARIUS',
        canReceiveSocietyInvoice: true,
        taxCollectAccounts: ['food', 'safe_food'],
    },
    [JobType.News]: {
        label: 'Truyền hình Twitch News',
        platePrefix: 'NEWS',
        menuCallback: ClientEvent.JOBS_TWITCH_NEWS_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            ...NewsPermissions,
            ...CompanyPanelPermissions,
        },
        bossZones: [
            {
                center: [-576.17, -937.34, 28.82],
                length: 5.8,
                width: 10.8,
                heading: 0,
                minZ: 27.82,
                maxZ: 31.82,
            },
        ],
        phone: '555-NEWS',
        canReceiveSocietyInvoice: true,
    },
    [JobType.YouNews]: {
        label: 'Truyền hình You News',
        platePrefix: 'YOUN',
        menuCallback: ClientEvent.JOBS_YOU_NEWS_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            ...NewsPermissions,
            ...CompanyPanelPermissions,
        },
        bossZones: [
            { center: [-1054.43, -232.09, 44.02], length: 6.2, width: 5.8, heading: 116.65, minZ: 43.02, maxZ: 45.02 },
        ],
        phone: '555-YOUN',
        canReceiveSocietyInvoice: true,
    },
    [JobType.Garbage]: {
        label: 'Vệ sinh Môi trường (BlueBird)',
        platePrefix: 'BLUE',
        menuCallback: ClientEvent.JOBS_GARBAGE_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            ...CompanyPanelPermissions,
        },
        bossZones: [
            {
                center: [-620.23, -1620.86, 33.01],
                length: 8.0,
                width: 11.8,
                heading: 355,
                minZ: 32.01,
                maxZ: 36.01,
            },
        ],
        phone: '555-BLUEBIRD',
        canReceiveSocietyInvoice: true,
        taxCollectAccounts: ['garbage', 'safe_garbage'],
    },
    [JobType.Oil]: {
        label: 'Vận tải & Xăng dầu (MTP)',
        platePrefix: 'MITP',
        menuCallback: ClientEvent.JOBS_OIL_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.FuelerChangePrice]: { label: 'Thay đổi giá các trạm xăng công cộng' },
            ...CompanyPanelPermissions,
        },
        bossZones: [
            {
                center: [-242.74, 6070.52, 40.61],
                length: 13.4,
                width: 4.6,
                heading: 315,
                minZ: 39.61,
                maxZ: 42.61,
            },
        ],
        phone: '555-MTP',
        canReceiveSocietyInvoice: true,
        taxCollectAccounts: ['oil', 'safe_oil'],
    },
    [JobType.CashTransfer]: {
        label: 'An ninh & Chở tiền (STONK)',
        platePrefix: 'STNK',
        menuCallback: ClientEvent.JOBS_STONK_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.CashTransfer_CollectSecure]: { label: 'Thu gom thùng tiền bảo mật' },
            [JobPermission.CashTransfer_CollectBags]: { label: 'Thu gom túi tiền' },
            [JobPermission.CashTransfer_ResaleBags]: { label: 'Giao nộp túi tiền' },
            [JobPermission.CashTransfer_FillIn]: { label: 'Nạp tiền vào Ngân hàng / Cây ATM' },
            [JobPermission.CashTransfer_AccountAccess]: { label: 'Truy cập két sắt bảo mật doanh nghiệp' },
            ...CompanyPanelPermissions,
        },
        bossZones: [
            {
                center: [-17.97, -705.88, 46.02],
                length: 7.8,
                width: 4.4,
                heading: 25,
                minZ: 45.02,
                maxZ: 49.02,
            },
        ],
        phone: '555-STONK',
        canReceiveSocietyInvoice: true,
    },
    [JobType.Bennys]: {
        label: 'Gara Sửa xe (New Gahray)',
        platePrefix: 'NEWG',
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.BennysEstimate]: { label: 'Định giá phương tiện' },
            [JobPermission.Order]: { label: 'Đặt mua phương tiện thử nghiệm' },
            [JobPermission.BennysResell]: { label: 'Bán lại phương tiện' },
            [JobPermission.BennysPitStopPrice]: { label: 'Thay đổi giá dịch vụ Pit Stop' },
            ...CompanyPanelPermissions,
        },
        bossZones: [
            {
                center: [-204.51, -1336.96, 34.89],
                length: 15.8,
                width: 3.4,
                heading: 0,
                minZ: 33.89,
                maxZ: 37.89,
            },
            new BoxZone([1908.1, 3086.76, 51.75], 18.4, 9.2, {
                heading: 61.21,
                minZ: 50.75,
                maxZ: 52.75,
            }),
        ],
        phone: '555-NEWGAHRAY',
        canReceiveSocietyInvoice: true,
        taxCollectAccounts: ['bennys', 'safe_bennys'],
    },
    [JobType.Upw]: {
        label: 'Điện & Nước (UPW)',
        platePrefix: 'UPW',
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.Order]: { label: 'Đặt mua xe điện chuyên dụng' },
            ...CompanyPanelPermissions,
        },
        bossZones: [
            {
                center: [604.3, 2765.85, 47.76],
                length: 11.2,
                width: 11.8,
                heading: 4,
                minZ: 46.76,
                maxZ: 50.76,
            },
        ],
        phone: '555-UPW',
        canReceiveSocietyInvoice: true,
        taxCollectAccounts: ['upw', 'safe_upw'],
    },
    [JobType.Pawl]: {
        label: 'Khai thác & Chế biến Gỗ (PAWL)',
        platePrefix: 'PAWL',
        menuCallback: ClientEvent.PAWL_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            ...CompanyPanelPermissions,
        },
        resell: {
            primary: {
                coords: [-272.22, -2496.57, 7.3, 186.72],
                ZoneName: 'Resell:LSPort:Pawl',
                SourceAccount: 'farm_pawl',
                TargetAccount: 'safe_pawl',
            },
            secondary: { ZoneName: 'Resell:Zkea', SourceAccount: 'farm_pawl', TargetAccount: 'safe_pawl' },
        },
        bossZones: [
            {
                center: [-539.85, 5300.99, 76.37],
                length: 9.4,
                width: 10.8,
                heading: 341,
                minZ: 75.37,
                maxZ: 79.37,
            },
        ],
        phone: '555-PAWL',
        canReceiveSocietyInvoice: true,
        taxCollectAccounts: ['pawl', 'safe_pawl'],
    },
    [JobType.Baun]: {
        label: 'Quán Bar (Bahama Unicorn)',
        platePrefix: 'BAUN',
        menuCallback: ClientEvent.JOBS_BAUN_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.Harvest]: { label: 'Thu hoạch nguyên liệu pha chế' },
            [JobPermission.Restock]: { label: 'Bổ sung vật tư quầy bar' },
            [JobPermission.Craft]: { label: 'Pha chế Cocktail & Đồ uống' },
            ...CompanyPanelPermissions,
        },
        bossZones: [
            {
                center: [96.11, -1292.08, 29.27],
                length: 7.2,
                width: 6.2,
                heading: 300,
                minZ: 28.27,
                maxZ: 32.27,
            },
            {
                center: [-1387.87, -631.19, 30.81],
                length: 5.4,
                width: 6.4,
                heading: 303,
                minZ: 29.81,
                maxZ: 33.81,
            },
        ],
        phone: '555-BAUN',
        canReceiveSocietyInvoice: true,
        taxCollectAccounts: ['baun', 'safe_baun'],
    },
    [JobType.Ffs]: {
        label: 'Tiệm May & Thời trang (FFS)',
        platePrefix: 'FFS',
        menuCallback: ClientEvent.JOBS_FFS_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.Harvest]: { label: 'Thu thập vải & nguyên liệu may' },
            [JobPermission.Restock]: { label: 'Bổ sung vật tư xưởng may' },
            [JobPermission.Craft]: { label: 'May vá & Thiết kế trang phục' },
            ...CompanyPanelPermissions,
        },
        bossZones: [
            {
                center: [706.83, -965.59, 30.41],
                length: 6.0,
                width: 6.0,
                heading: 0,
                minZ: 29.41,
                maxZ: 33.41,
            },
        ],
        phone: '555-FFS',
        canReceiveSocietyInvoice: true,
        taxCollectAccounts: ['ffs', 'safe_ffs'],
    },
    [JobType.MDR]: {
        label: 'Tòa án & Tư pháp (Mandatory)',
        platePrefix: 'MDR',
        menuCallback: ClientEvent.JOBS_MDR_OPEN_SOCIETY_MENU,
        permissions: {
            ...BasePermissions,
            [JobPermission.VehicleRegistrar]: { label: 'Truy cập sổ đăng ký phương tiện' },
            [JobPermission.Investigation]: { label: 'Truy cập hồ sơ điều tra' },
            [JobPermission.ManageInvestigation]: { label: 'Quản lý hồ sơ điều tra' },
            [JobPermission.MdrViewCitizenData]: { label: 'Truy cập hồ sơ tiền án tiền sự' },
            [JobPermission.MdrEditCitizenData]: { label: 'Xóa bản án trong hồ sơ tiền án tiền sự' },
            [JobPermission.InvestigationLawyer]: { label: 'Luật sư tham gia điều tra' },
            [JobPermission.InvestigationProsecutor]: { label: 'Công tố viên tham gia điều tra' },
            [JobPermission.MdrViewOtherJobs]: { label: 'Truy cập thông tin các doanh nghiệp' },
            [JobPermission.MdrMarkedMoneyCleaning]: { label: 'Truy cập quy đổi tiền sạch' },
            [JobPermission.ManageRoster]: { label: 'Quản lý ảnh/mã số nhân sự trên panel' },
        },
        bossZones: [
            {
                center: [-546.36, -201.78, 47.66],
                length: 8.0,
                width: 17.0,
                heading: 30.0,
                minZ: 46.66,
                maxZ: 49.66,
            },
        ],
        canInvoice: true,
        phone: '555-MDR',
        canReceiveSocietyInvoice: true,
    },
    [JobType.Gouv]: {
        label: 'Chính phủ & Tòa thị chính',
        platePrefix: 'GOUV',
        menuCallback: ClientEvent.JOBS_GOUV_OPEN_SOCIETY_MENU,
        permissions: {
            ...BasePermissions,
            [JobPermission.GouvUpdateTax]: { label: 'Cập nhật mức thuế suất' },
            [JobPermission.GouvManageRadar]: { label: 'Quản lý camera bắn tốc độ (Radar)' },
            [JobPermission.GouvManageFine]: { label: 'Thêm, sửa và xóa các mức phạt' },
            [JobPermission.VehicleRegistrar]: { label: 'Truy cập sổ đăng ký xe trên panel' },
            [JobPermission.VehicleTransfert]: { label: 'Truy cập chuyển nhượng xe trên panel' },
            [JobPermission.MdrViewCitizenData]: { label: 'Truy cập hồ sơ tiền án tiền sự' },
            [JobPermission.Craft]: { label: 'Ký duyệt văn bản & giấy tờ chính thức' },
        },
        bossZones: [
            {
                center: [-526.8, -597.0, 34.68],
                length: 8.8,
                width: 17.6,
                heading: 90.0,
                minZ: 33.68,
                maxZ: 35.68,
            },
        ],
        canInvoice: true,
        phone: '555-GOUV',
        canReceiveSocietyInvoice: true,
    },
    [JobType.SASP]: {
        label: 'Cảnh sát Tiểu bang (SASP)',
        platePrefix: 'SASP',
        menuCallback: ClientEvent.JOBS_POLICE_OPEN_SOCIETY_MENU,
        permissions: {
            ...BasePermissions,
            ...PolicePermissions,
        },
        bossZones: [
            {
                center: [-584.16, -593.97, 34.68],
                length: 8.4,
                width: 11.6,
                heading: 90.0,
                minZ: 33.68,
                maxZ: 35.68,
            },
            // MIRROR PARK
            {
                center: [1147.86, -466.25, 72.62],
                length: 28.2,
                width: 33.6,
                heading: 166.7,
                minZ: 71.62,
                maxZ: 73.62,
            },
        ],
        canInvoice: true,
        phone: '555-SASP',
        canReceiveSocietyInvoice: true,
    },
    [JobType.FDF]: {
        label: 'Nông trại (Ferme de Fou)',
        platePrefix: 'FDF',
        menuCallback: ClientEvent.JOBS_FDF_OPEN_SOCIETY_MENU,
        permissions: {
            ...BasePermissions,
            ...CompanyPanelPermissions,
        },
        bossZones: [
            {
                center: [2443.96, 4974.61, 47.39],
                length: 23.2,
                width: 47.8,
                heading: 226.09,
                minZ: 44.39,
                maxZ: 55.39,
            },
        ],
        canInvoice: true,
        phone: '555-FDF',
        canReceiveSocietyInvoice: true,
        taxCollectAccounts: ['fdf', 'safe_fdf'],
    },
    [JobType.DMC]: {
        label: 'Khai thác & Luyện kim (DMC)',
        platePrefix: 'DMC',
        menuCallback: ClientEvent.JOBS_DMC_OPEN_SOCIETY_MENU,
        permissions: {
            ...BasePermissions,
            ...CompanyPanelPermissions,
        },
        bossZones: [
            {
                center: [1077.99, -1979.487, 31.37],
                length: 7.8,
                width: 4.2,
                heading: 235.7,
                minZ: 30.37,
                maxZ: 32.97,
            },
        ],
        canInvoice: true,
        phone: '555-DMC',
        canReceiveSocietyInvoice: true,
        resell: {
            primary: {
                //coords: [-132.7, -2383.92, 6.0, 174.18],
                coords: [-334.31, -1314.83, 31.4, 87.04],
                ZoneName: 'Resell:LSPort:Dmc',
                SourceAccount: 'farm_dmc',
                TargetAccount: 'safe_dmc',
            },
            secondary: { ZoneName: 'Resell:LSCustom', SourceAccount: 'farm_dmc', TargetAccount: 'safe_dmc' },
        },
        taxCollectAccounts: ['dmc', 'safe_dmc'],
    },
    [JobType.Casino]: {
        label: 'Diamond Casino',
        platePrefix: 'DIAM',
        permissions: BasePermissions,
        bossZones: [
            {
                center: [958.25, 58.3, 75.44],
                length: 10.6,
                width: 9.2,
                heading: 149.4,
                minZ: 74.44,
                maxZ: 77.44,
            },
        ],
        canInvoice: true,
        phone: '555-DIAMOND',
        canReceiveSocietyInvoice: true,
        taxCollectAccounts: ['casino', 'safe_casino'],
    },
};

export const JobBossZoneWhatIf: Partial<Record<JobType, Zone[]>> = {
    [JobType.SASP]: [
        {
            center: [626.23, -24.0, 90.51],
            length: 16.2,
            width: 16.4,
            heading: 340,
            minZ: 89.51,
            maxZ: 92.51,
        },
    ],
};
